### ISSUE TITLE
Не отключается вывод логирования клавишь keyDetector

### ISSUE THREAD

**Issue by niksher23** [uzyovoys/aggregate#48]
В конфиге прописано 
{
    "skip-logs" : true,
    "key-codes" : [164, 91]

}
Две клавиши определяет правильно, но логирование не отключает.

**Comment by UUSR** [comment]
@niksher23 у меня в конфиге:
{
  "key-codes" : [3]
  "skip-logs" : true
}
Логироваание вообще не работает и кнопка мыши вообше не определяется.

**Comment by morfeusys** [comment]
@niksher23 соберите новую версию сперва
@UUSR заводите отдельный issue если считаете что что-то не рабоатет

**Comment by niksher23** [comment]
@Morfeusys  надо самому скомпелировать или можно скачать готовый модуль? Вижу ссылку только на версию 1.0.0. и обновленные исходники.

**Comment by morfeusys** [comment]
@niksher23 сейчас компилить нужно самому. Автобилды еще не подняли.

**Comment by UUSR** [comment]
@Morfeusys заводить issue пока не буду ,я ешё не всё проверил.
Скомпилировать с новыми исходными данными пока не могу,
**вот вывод ошибок:**
[INFO] BUILD FAILURE
[INFO] Total time: 6.906 s
[INFO] Finished at: 2016-03-08T16:58:06+01:00
[INFO] Final Memory: 7M/17M
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project key-detector: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Вывод ошибок из aggregate:**
мар 09, 2016 1:28:47 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
io.vertx.core.json.DecodeException: Failed to decode:Unexpected character ('"' (code 34)): was expecting comma
 to separate OBJECT entries
 at [Source: {
  "key-codes" : [3]
  "skip-logs" : true
}
; line: 3, column: 4]
        at io.vertx.core.json.Json.decodeValue(Unknown Source)
        at io.vertx.core.json.JsonObject.fromJson(Unknown Source)
        at io.vertx.core.json.JsonObject.<init>(Unknown Source)
        at io.vertx.core.buffer.impl.BufferImpl.toJsonObject(Unknown Source)
        at io.vertx.core.ay.a(Unknown Source)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(Unknown Source)
        at io.vertx.core.impl.FutureImpl.setHandler(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$null$16(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Unknown Source)
        at io.netty.channel.nio.NioEventLoop.run(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

мар 09, 2016 1:28:47 AM vertx-stack-resolver

**Попытка компиляции с новыми входящими данными:**
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.860 s
[INFO] Finished at: 2016-03-09T01:53:32+01:00
[INFO] Final Memory: 8M/22M
[INFO] ------------------------------------------------------------------------
FATAL ERROR in native method: JDWP on getting class status, jvmtiError=JVMTI_ERROR_WRONG_PHASE(112)
#

# A fatal error has been detected by the Java Runtime Environment:

#

# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x6dbba9d5, pid=3288, tid=3268

#

# JRE version: Java(TM) SE Runtime Environment (8.0_73-b02) (build 1.8.0_73-b02)

# Java VM: Java HotSpot(TM) Client VM (25.73-b02 mixed mode windows-x86 )

# Problematic frame:

# C  [jdwp.dll+0x1a9d5]JDWP exit error JVMTI_ERROR_WRONG_PHASE(112): on getting class status [util.c:1285]

**Comment by ivanbalashov239** [comment]
@UUSR  лучше заводите issue на каждый чих, багов много не бывает, если окажется не актуально, закроем.

**Comment by morfeusys** [comment]
@UUSR Строчка говорит сама за себя Perhaps you are running on a JRE rather than a JDK?
Зайдите в настройки эклипса, Java, Java compiler. Установите там JDK вместо JRE.

**Comment by UUSR** [comment]
@Morfeusys сделал ещё в самом начале после установки Eclipse до импорта проекта.

**Comment by niksher23** [comment]
Скомпилировал keydetector 1.1 встал. Отключение логов сработало.

**Comment by ivanbalashov239** [comment]
@niksher23 отлично, полагаю issue можно закрывать.

**Comment by UUSR** [comment]
@seniorivn я согласен ,я догоню вас позже так как у меня не всё ещё настроено на локалке.

**Comment by Menelion** [comment]
У меня issue не исчез: 1.0.1 встал, однако логирование не отключается. Windows 7 32 bit, Java 8 update 73.

**Comment by UUSR** [comment]
@Morfeusys  скомпилил key-detector 1.1.0 ,установил всё работает без проблем ,**логирование отключается.**
После компиляции получил такую ошибку:
[INFO] ------------------------------------------------------------------------
FATAL ERROR in native method: JDWP on getting class status, jvmtiError=JVMTI_ERROR_WRONG_PHASE(112)

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x6dbba9d5, pid=3288, tid=3268

 JRE version: Java(TM) SE Runtime Environment (8.0_73-b02) (build 1.8.0_73-b02)
 Java VM: Java HotSpot(TM) Client VM (25.73-b02 mixed mode windows-x86 )
 Problematic frame:
 C  [jdwp.dll+0x1a9d5]JDWP exit error JVMTI_ERROR_WRONG_PHASE(112): on getting class  status [util.c:1285]

@Oire пробуйте ещё раз ,у вас всё получится.

**Comment by morfeusys** [comment]
@Oire старую версию не забудь удалить руками - в агрегате сейчас с обновлениями туго..

**Comment by Menelion** [comment]
Сорри, туплю: а откуда удалить? Только из `aggregate.json`?

**Comment by UUSR** [comment]
@Oire удаляйте и из "aggregate.json" в секции "modules" и из директории \repository\com\aggregate\my-module удалите всю папку с модулем.
